// <auto-generated />
namespace ExpressQuiz.Core.Migrations.Application
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class App_Init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(App_Init));
        
        string IMigrationMetadata.Id
        {
            get { return "201408281547335_App_Init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
