// <auto-generated />
namespace ExpressQuiz.Core.Migrations.Quiz
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class moretext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(moretext));
        
        string IMigrationMetadata.Id
        {
            get { return "201409041449474_moretext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
